/**
 * CoPilotFeed.jsx — Floating AI Co-Pilot advisory notification center.
 *
 * Displays a scrollable, timestamped feed of alerts generated by the
 * backend physics engine's rule-based advisory system. Each alert has
 * a severity badge, icon, title, and detail text.
 */

import { useRef, useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  BrainCircuit, AlertTriangle, CheckCircle2, XOctagon, Info,
  ChevronDown, ChevronUp, Bell, Trash2,
} from "lucide-react";

const SEVERITY_CONFIG = {
  warning: {
    icon: AlertTriangle,
    color: "#f59e0b",
    bg: "rgba(245, 158, 11, 0.08)",
    border: "rgba(245, 158, 11, 0.20)",
    emoji: "⚠️",
  },
  success: {
    icon: CheckCircle2,
    color: "#22c55e",
    bg: "rgba(34, 197, 94, 0.08)",
    border: "rgba(34, 197, 94, 0.20)",
    emoji: "🟢",
  },
  danger: {
    icon: XOctagon,
    color: "#ef4444",
    bg: "rgba(239, 68, 68, 0.08)",
    border: "rgba(239, 68, 68, 0.20)",
    emoji: "🔴",
  },
  info: {
    icon: Info,
    color: "#38bdf8",
    bg: "rgba(56, 189, 248, 0.08)",
    border: "rgba(56, 189, 248, 0.20)",
    emoji: "💡",
  },
};

function AlertCard({ alert, index }) {
  const cfg = SEVERITY_CONFIG[alert.severity] || SEVERITY_CONFIG.info;
  const Icon = cfg.icon;

  return (
    <motion.div
      layout
      initial={{ opacity: 0, x: -20, scale: 0.95 }}
      animate={{ opacity: 1, x: 0, scale: 1 }}
      exit={{ opacity: 0, x: 20, scale: 0.95 }}
      transition={{ type: "spring", stiffness: 300, damping: 25, delay: index * 0.03 }}
      className="rounded-xl p-2.5 mb-1.5 border"
      style={{ background: cfg.bg, borderColor: cfg.border }}
    >
      <div className="flex items-start gap-2">
        {/* Severity icon */}
        <div
          className="w-6 h-6 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
          style={{ background: `${cfg.color}18` }}
        >
          <Icon size={13} style={{ color: cfg.color }} />
        </div>

        <div className="flex-1 min-w-0">
          {/* Header: title + timestamp */}
          <div className="flex items-center justify-between mb-0.5">
            <span className="text-[10px] font-semibold text-white leading-none truncate">
              {cfg.emoji} {alert.title}
            </span>
            <span className="text-[8px] text-slate-500 font-mono shrink-0 ml-2">
              t={alert.time.toFixed(1)}m
            </span>
          </div>

          {/* Detail text */}
          <p className="text-[9px] text-slate-400 leading-relaxed">
            {alert.detail}
          </p>
        </div>
      </div>
    </motion.div>
  );
}

export default function CoPilotFeed({ alerts = [], onClear }) {
  const [expanded, setExpanded] = useState(true);
  const scrollRef = useRef(null);
  const prevLength = useRef(0);

  // Auto-scroll to bottom when new alerts arrive
  useEffect(() => {
    if (alerts.length > prevLength.current && scrollRef.current) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: "smooth",
      });
    }
    prevLength.current = alerts.length;
  }, [alerts.length]);

  const unreadCount = alerts.length;

  return (
    <motion.div
      layout
      className="glass flex flex-col"
      style={{ maxHeight: expanded ? "380px" : "44px", overflow: "hidden" }}
      animate={{ height: expanded ? "auto" : 44 }}
      transition={{ type: "spring", stiffness: 250, damping: 28 }}
    >
      {/* Header bar */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex items-center justify-between px-3 py-2.5 shrink-0
                   hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-violet-500/20 to-sky-500/20
                         flex items-center justify-center">
            <BrainCircuit size={13} className="text-violet-400" />
          </div>
          <span className="text-[10px] font-bold text-white uppercase tracking-wider">
            AI Co-Pilot
          </span>
          {unreadCount > 0 && (
            <motion.span
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              className="text-[8px] font-bold px-1.5 py-0.5 rounded-full
                        bg-violet-500/20 text-violet-300 border border-violet-500/30"
            >
              {unreadCount}
            </motion.span>
          )}
        </div>
        <div className="flex items-center gap-1">
          {expanded && alerts.length > 0 && (
            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              onClick={(e) => {
                e.stopPropagation();
                onClear?.();
              }}
              className="w-5 h-5 rounded-md flex items-center justify-center
                        hover:bg-white/5 text-slate-500 hover:text-slate-300 transition-colors"
            >
              <Trash2 size={10} />
            </motion.button>
          )}
          {expanded ? (
            <ChevronDown size={13} className="text-slate-500" />
          ) : (
            <ChevronUp size={13} className="text-slate-500" />
          )}
        </div>
      </button>

      {/* Alert feed */}
      {expanded && (
        <div
          ref={scrollRef}
          className="flex-1 overflow-y-auto overflow-x-hidden px-2.5 pb-2"
          style={{ maxHeight: "330px" }}
        >
          {alerts.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-6 text-center">
              <Bell size={20} className="text-slate-600 mb-2" />
              <p className="text-[10px] text-slate-500">
                No advisories yet. Start the simulation to receive real-time guidance.
              </p>
            </div>
          ) : (
            <AnimatePresence mode="popLayout">
              {alerts.map((alert, i) => (
                <AlertCard key={`${alert.tag}-${alert.time}`} alert={alert} index={i} />
              ))}
            </AnimatePresence>
          )}
        </div>
      )}
    </motion.div>
  );
}
